### ISSUE TITLE
연락 부탁드려요

### ISSUE THREAD

**Issue by lunDreame** [chongjae/smartthings#1]
안녕하세요 bestintcp 문제란에 질문 올리신적이 있길래 혹시 성공 하셨으면 적용 방법좀 여쭤볼라 하는데 카카오톡으로 연락좀 부탁드려도 될까요..? 계속 시도하고 있는데 어렵네요

**Comment by chongjae** [comment]
TCP방식은 BESTIN 1.0만 가능한 것 같더라구요.
 
2.0은 암호화되어있는 거 까지만 확인했습니다.
 
그래서, HTTP 방식으로 연동했습니다~
https://cafe.naver.com/stsmarthome/38266 
 
-----Original Message-----
From: ***@***.***>
To: ***@***.***>;
Cc: ***@***.***>;
Sent: 2022-02-26 (토) 00:30:26 (GMT+09:00)
Subject: [chongjae/smartthings] 연락 부탁드려요 (Issue #1)
 
안녕하세요 bestintcp 문제란에 질문 올리신적이 있길래 혹시 성공 하셨으면 적용 방법좀 여쭤볼라 하는데 카카오톡 harwin으로 연락좀 부탁드려도 될까요..? 계속 시도하고 있는데 어렵네요
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
